## Erman Parni Simanjuntak
## 2009106046
## POSTTEST 7

#### Import Library

In [3]:
import tensorflow as tf

#### tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [4]:
rt = tf.random.normal([5,5],mean=0,stddev=1,seed=1) 
print(rt)

tf.Tensor(
[[-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
 [ 0.5912243   0.59282297 -2.1229296  -0.72289723 -0.05627038]
 [ 0.6435448  -0.26432407  1.8566332   0.5678417  -0.3828359 ]
 [-1.4853433   1.2617711  -0.02530608 -0.2646297   1.5328138 ]
 [-1.7429771  -0.43789294 -0.56601     0.32066926  1.132831  ]], shape=(5, 5), dtype=float32)


#### shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [5]:
list = [[1,3,5,8,11],[15,16,19,23,25],[32,34,44,45,47],[55,58,65,67,70],[71,75,82,87,91]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)
prime_tensor.numpy()

array([[ 1.,  3.,  5.,  8., 11.],
       [15., 16., 19., 23., 25.],
       [32., 34., 44., 45., 47.],
       [55., 58., 65., 67., 70.],
       [71., 75., 82., 87., 91.]], dtype=float32)

#### Tampilkan dimensi dari kedua variable tersebut

In [6]:
rt.get_shape()

TensorShape([5, 5])

In [7]:
rt.shape

TensorShape([5, 5])

## Hasil dari perhitungan aritmetika 2 variable

#### Tambah

In [8]:
print(tf.add(rt, prime_tensor))

tf.Tensor(
[[ 0.18868178  4.4845986   5.0653296   5.557296   11.099248  ]
 [15.591225   16.592823   16.877071   22.277103   24.94373   ]
 [32.643543   33.735676   45.856632   45.56784    46.617165  ]
 [53.514656   59.261772   64.97469    66.73537    71.532814  ]
 [69.25702    74.5621     81.43399    87.32067    92.13283   ]], shape=(5, 5), dtype=float32)


#### kali

In [9]:
print(tf.multiply(rt, prime_tensor))

tf.Tensor(
[[  -0.8113182     4.4537964     0.32664686  -19.541634      1.0917324 ]
 [   8.868364      9.4851675   -40.335663    -16.626637     -1.4067595 ]
 [  20.593433     -8.987019     81.691864     25.552877    -17.993286  ]
 [ -81.693886     73.182724     -1.6448952   -17.73019     107.29697   ]
 [-123.75137     -32.841972    -46.41282      27.898226    103.087616  ]], shape=(5, 5), dtype=float32)


#### kurang

In [10]:
print(tf.subtract(rt, prime_tensor))

tf.Tensor(
[[ -1.8113182  -1.5154012  -4.9346704 -10.442704  -10.900752 ]
 [-14.408775  -15.407177  -21.122929  -23.722897  -25.05627  ]
 [-31.356455  -34.264324  -42.143368  -44.43216   -47.382835 ]
 [-56.485344  -56.738228  -65.02531   -67.26463   -68.467186 ]
 [-72.74298   -75.4379    -82.56601   -86.67933   -89.86717  ]], shape=(5, 5), dtype=float32)


#### pembagian

In [11]:
print(tf.divide(rt,prime_tensor))

tf.Tensor(
[[-8.1131822e-01  4.9486625e-01  1.3065875e-02 -3.0533803e-01
   9.0225823e-03]
 [ 3.9414953e-02  3.7051436e-02 -1.1173314e-01 -3.1430315e-02
  -2.2508153e-03]
 [ 2.0110775e-02 -7.7742375e-03  4.2196210e-02  1.2618705e-02
  -8.1454450e-03]
 [-2.7006242e-02  2.1754675e-02 -3.8932430e-04 -3.9496967e-03
   2.1897340e-02]
 [-2.4548974e-02 -5.8385725e-03 -6.9025611e-03  3.6858537e-03
   1.2448692e-02]], shape=(5, 5), dtype=float32)


#### Pangkat

In [12]:
print(tf.pow(rt, prime_tensor))

tf.Tensor(
[[-8.1131822e-01  3.2721055e+00  1.1899876e-06  1.2675557e+03
   9.2036214e-12]
 [ 3.7695045e-04  2.3270212e-04 -1.6284565e+06 -5.7380047e-04
  -5.7147351e-32]
 [ 7.4906757e-07  2.2524138e-20  6.6672814e+11  8.7142099e-12
  -2.5211261e-20]
 [-2.8214794e+09  7.1923875e+05 -0.0000000e+00 -0.0000000e+00
   9.6440146e+12]
 [-1.3542851e+17 -1.2664732e-27  5.3898471e-21  0.0000000e+00
   8.4923055e+04]], shape=(5, 5), dtype=float32)


#### Logaritma

In [13]:
print(tf.math.log(rt, prime_tensor))

tf.Tensor(
[[        nan  0.39514455 -2.7283134          nan -2.3101294 ]
 [-0.5255598  -0.52285945         nan         nan         nan]
 [-0.44076362         nan  0.61876476 -0.5659126          nan]
 [        nan  0.23251635         nan         nan  0.42710513]
 [        nan         nan         nan -1.1373451   0.12471979]], shape=(5, 5), dtype=float32)


## Nilai Max & Min

#### Min

In [14]:
print(tf.argmin(rt, axis=0))

tf.Tensor([4 4 1 0 2], shape=(5,), dtype=int64)


In [15]:
print(tf.argsort(rt, direction='ASCENDING'))

tf.Tensor(
[[3 0 2 4 1]
 [2 3 4 0 1]
 [4 1 3 0 2]
 [0 3 2 1 4]
 [0 2 1 3 4]], shape=(5, 5), dtype=int32)


In [16]:
print(tf.argmin(rt, axis=1))

tf.Tensor([3 2 4 0 0], shape=(5,), dtype=int64)


In [17]:
print(tf.sort(rt, direction='ASCENDING'))

tf.Tensor(
[[-2.4427042  -0.8113182   0.06532937  0.0992484   1.4845988 ]
 [-2.1229296  -0.72289723 -0.05627038  0.5912243   0.59282297]
 [-0.3828359  -0.26432407  0.5678417   0.6435448   1.8566332 ]
 [-1.4853433  -0.2646297  -0.02530608  1.2617711   1.5328138 ]
 [-1.7429771  -0.56601    -0.43789294  0.32066926  1.132831  ]], shape=(5, 5), dtype=float32)


#### Max

In [18]:
print(tf.argmax(rt, axis=0))

tf.Tensor([2 0 2 2 3], shape=(5,), dtype=int64)


In [19]:
print(tf.argsort(rt, direction='ASCENDING'))

tf.Tensor(
[[3 0 2 4 1]
 [2 3 4 0 1]
 [4 1 3 0 2]
 [0 3 2 1 4]
 [0 2 1 3 4]], shape=(5, 5), dtype=int32)


#### Concatenation

In [20]:
print("size original data : ",prime_tensor.shape,rt.shape)
list_prima_tensor = tf.concat([prime_tensor,rt],axis=0)
print("size concat data : ",prime_tensor.shape)

size original data :  (5, 5) (5, 5)
size concat data :  (5, 5)


#### Hasil sorting dari kedua variable di atas. (descending)

In [21]:
print(tf.sort(rt, direction="DESCENDING"))
print(tf.sort(prime_tensor, direction="DESCENDING"))

tf.Tensor(
[[ 1.4845988   0.0992484   0.06532937 -0.8113182  -2.4427042 ]
 [ 0.59282297  0.5912243  -0.05627038 -0.72289723 -2.1229296 ]
 [ 1.8566332   0.6435448   0.5678417  -0.26432407 -0.3828359 ]
 [ 1.5328138   1.2617711  -0.02530608 -0.2646297  -1.4853433 ]
 [ 1.132831    0.32066926 -0.43789294 -0.56601    -1.7429771 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[11.  8.  5.  3.  1.]
 [25. 23. 19. 16. 15.]
 [47. 45. 44. 34. 32.]
 [70. 67. 65. 58. 55.]
 [91. 87. 82. 75. 71.]], shape=(5, 5), dtype=float32)
